

function submitted(event) {
  event.preventDefault();
  const url = google + site + '+' + q.value;
  const win = window.open(url, '_blank');
  win.focus();
}


f.addEventListener('submit', submitted);


function secretFunction() {
    alert("IS LE SECRET BUTTON BOTHERING YOU QUEEN? DM ME IF WE NEED TO TALK");
}


<CENTER> {
<script language="JavaScript">
var count = "countometer";          // Change Your Account?
var type = "fdg";       // Change Your Counter Image?
var digits = "30";          // Change The Amount of Digits on Your Counter?
var prog = "hit";          // Change to Either hit/unique?
var statslink = "no";    // provide statistical link in counter yes/no?
var sitelink = "yes";     // provide link back to our site;~) yes/no?
var cntvisible = "yes"; // do you want counter visible yes/no?
</script>
<!-- START DO NOT TAMPER WITH ANYTHING ELSE BELOW THIS LINE FOR YOUR WEBTV & UNIX VISITORS -->
<script language="JavaScript" src="http://006.free-counters.co.uk/count-123.js">
</script>
<noscript>
<a href="http://www.free-counters.co.uk" target="_blank">
<img  src="http://006.free-counters.co.uk/count-123.pl?count=countometer&cntvisible=no&mode=noscript" alt="Free Counters" title="Free Counters" border="0">
</a>The following text will not be seen after you upload your website,
please keep it in order to retain your counter functionality 
<br><a href="http://www.free-counters.co.uk" target="_blank">Free Trackers</a><br> <a href="http://www.free-counters.co.uk" target="_blank">Help</a><br>

</noscript>
<!-- END DO NOT TAMPER WITH ANYTHING ELSE ABOVE THIS LINE FOR YOUR WEBTV & UNIX VISITORS -->
</CENTER>        
<!-- End of Globel Code -->
}
